server:
  port: 8083
spring:
  application:
    name: eureka-service
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8082/eureka
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）